import Head from "next/head";
import { Breadcrumb } from "../components/breadcrumb/Breadcrumb";
import { Footer } from "../components/footer/Footer";
import { Heading } from "../components/heading/Heading";
import { Links } from "../components/links/Links";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading />
        <Breadcrumb />
        <Links />
      </main>

      <Footer />
    </div>
  );
}
